{% set version = "0.3.0" %}
{% set python_min = python_min|default("3.9") %}

package:
  name: spacy-curated-transformers
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/s/spacy_curated_transformers/spacy_curated_transformers-{{ version }}.tar.gz
  sha256: 989a6bf2aa7becd1ac8c3be5f245cd489223d4e16e7218f6b69479c7e2689937

build:
  noarch: python
  script: python -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - curated-tokenizers >=0.0.9,<0.1.0
    - curated-transformers >=0.1.0,<0.2.0
    - pytorch >=1.12.0
    - spacy >=3.7.0,<4.0.0
    - srsly
    - thinc >=8.1.6,<9.1.0

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - spacy_curated_transformers
  commands:
    - pip check

about:
  home: https://github.com/explosion/spacy-curated-transformers
  summary: 'spaCy entry points for Curated Transformers'
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/explosion/spacy-curated-transformers

extra:
  recipe-maintainers:
    - h-vetinari
    - conda-forge/spacy
